name: Deployment (Container)
on:
  push:
    branches:
      - main
      - dev
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: gha-demo
jobs:
  test:
    environment: testing
    # steps on the 'test' job will run inside of the specified container, but still be hosted in the ubuntu-latest machine
    runs-on: ubuntu-latest
    #specify the name of the image (e.g. from dockerhub)
    container:
      image: node:16
      #env variables for the image (independent fomr job environments variables)
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      #here mongodb is the label of the service container as a connection address, github
      MONGODB_CLUSTER_ADDRESS: mongodb
      # MONGODB_CLUSTER_ADDRESS: cluster0.zcecven.mongodb.net
      MONGODB_USERNAME: root
      MONGODB_PASSWORD: example
      PORT: 8080
    # services allways run inside images
    services:
      # service container label used for networking
      mongodb:
        image: mongo
        #specify env variables, https://hub.docker.com/_/mongo
        env:
          #crential for new db inside the service
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: example
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT # requires MongoDB Atlas to accept requests from anywhere!
      - name: Run tests
        run: npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
